#!/usr/bin/env python3
"""Packs the PPSSPP assets the guest needs into a deterministic assets.zip.

Correctness content only: the VFPU lookup tables (the accurate CPU path reads
them through the VFS; without them the core falls back to the host libm and
the machine diverges), the PSP fonts (flash0), PPGe's atlas (savedata dialog
rendering), and the small ini databases boot consults. UI fonts, sounds,
langpacks and the like stay out.
"""
import os, sys, zipfile

mode = "zip"
args = [a for a in sys.argv[1:] if not a.startswith("--")]
if "--embed" in sys.argv:
    mode = "embed"
src = args[0] if len(args) > 0 else "../extern/ppsspp/assets"
out = args[1] if len(args) > 1 else ("bin/assets.zip" if mode == "zip" else "obj-guest")

WANT_DIRS = ["vfpu", "flash0", "lang"]
WANT_FILES = ["ppge_atlas.zim", "ppge_atlas.meta", "compat.ini", "compatvr.ini",
              "langregion.ini", "knownfuncs.ini"]

entries = []
for d in WANT_DIRS:
    for root, dirs, files in os.walk(os.path.join(src, d)):
        dirs.sort()
        for name in sorted(files):
            full = os.path.join(root, name)
            entries.append((os.path.relpath(full, src), full))
for f in WANT_FILES:
    full = os.path.join(src, f)
    if os.path.exists(full):
        entries.append((f, full))
entries.sort()

if mode == "embed":
    # Emit an .incbin assembly blob plus the name->span table the
    # MemoryAssetReader compiles against (see memory-assets.cpp).
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "assets.s"), "w") as a, \
         open(os.path.join(out, "assets-table.inc"), "w") as t:
        a.write('\t.section .rodata.chimassets,"a"\n')
        decls = []
        rows = []
        for i, (arc, full) in enumerate(entries):
            a.write(f"\t.globl _chim_asset_{i}\n_chim_asset_{i}:\n")
            a.write(f'\t.incbin "{os.path.abspath(full)}"\n')
            a.write(f"\t.globl _chim_asset_{i}_end\n_chim_asset_{i}_end:\n")
            decls.append(f'extern "C" const uint8_t _chim_asset_{i}[], _chim_asset_{i}_end[];')
            rows.append(f'\t{{ "{arc}", _chim_asset_{i}, _chim_asset_{i}_end }},')
        t.write("// generated by build-assets.py --embed; do not edit\n")
        t.write("\n".join(decls) + "\n\n")
        t.write("static const ChimAsset g_chimAssets[] = {\n" + "\n".join(rows) + "\n};\n")
    total = sum(os.path.getsize(f) for _, f in entries)
    print(f"{out}/assets.s: {len(entries)} files, {total} bytes embedded")
else:
    FIXED_DATE = (1980, 1, 1, 0, 0, 0)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for arc, full in entries:
            info = zipfile.ZipInfo(arc, date_time=FIXED_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.create_system = 3
            info.external_attr = 0o644 << 16
            with open(full, "rb") as f:
                z.writestr(info, f.read())
    print(f"{out}: {len(entries)} files, {os.path.getsize(out)} bytes")
