// A VFSBackend over assets compiled INTO the guest image (.rodata): the vfpu
// lookup tables (a CORRECTNESS requirement - without them the core falls back
// to the host libm and the machine depends on the build), the PSP fonts
// (flash0), PPGe's atlas, and the small ini databases. Embedding keeps the
// package two files and costs nothing at savestate time (read-only pages).
//
// The table and the .incbin blob are generated by build-assets.py into the
// object directory; see build-core.sh.
#include <cstdint>
#include <cstring>
#include <string>
#include <set>
#include <vector>

#include "Common/File/VFS/VFS.h"
#include "Common/File/DirListing.h"
#include "Common/File/Path.h"

#include "memory-assets.h"

struct ChimAsset {
	const char *name;
	const uint8_t *begin;
	const uint8_t *end;
};

#include "assets-table.inc"

namespace {

const ChimAsset *findAsset(std::string_view path) {
	for (size_t i = 0; i < sizeof(g_chimAssets) / sizeof(g_chimAssets[0]); i++)
		if (path == g_chimAssets[i].name)
			return &g_chimAssets[i];
	return nullptr;
}

struct MemRef : public VFSFileReference {
	const ChimAsset *asset;
};
struct MemOpen : public VFSOpenFile {
	const ChimAsset *asset;
	size_t pos;
};

class MemoryAssetReader : public VFSBackend {
public:
	uint8_t *ReadFile(std::string_view path, size_t *size) override {
		const ChimAsset *a = findAsset(path);
		if (!a)
			return nullptr;
		size_t n = (size_t)(a->end - a->begin);
		uint8_t *buf = new uint8_t[n + 1];
		memcpy(buf, a->begin, n);
		buf[n] = 0;  // matches DirectoryReader's convenience NUL
		*size = n;
		return buf;
	}

	VFSFileReference *GetFile(std::string_view path) override {
		const ChimAsset *a = findAsset(path);
		if (!a)
			return nullptr;
		MemRef *r = new MemRef();
		r->asset = a;
		return r;
	}

	bool GetFileInfo(VFSFileReference *ref, File::FileInfo *info) override {
		MemRef *r = (MemRef *)ref;
		if (info) {
			*info = File::FileInfo{};
			info->name = r->asset->name;
			info->fullName = Path(r->asset->name);
			info->exists = true;
			info->size = (uint64_t)(r->asset->end - r->asset->begin);
		}
		return true;
	}

	void ReleaseFile(VFSFileReference *ref) override { delete (MemRef *)ref; }

	VFSOpenFile *OpenFileForRead(VFSFileReference *ref, size_t *size) override {
		MemOpen *o = new MemOpen();
		o->asset = ((MemRef *)ref)->asset;
		o->pos = 0;
		if (size)
			*size = (size_t)(o->asset->end - o->asset->begin);
		return o;
	}

	void Rewind(VFSOpenFile *file) override { ((MemOpen *)file)->pos = 0; }

	size_t Read(VFSOpenFile *file, void *buffer, size_t length) override {
		MemOpen *o = (MemOpen *)file;
		size_t total = (size_t)(o->asset->end - o->asset->begin);
		size_t take = length < total - o->pos ? length : total - o->pos;
		memcpy(buffer, o->asset->begin + o->pos, take);
		o->pos += take;
		return take;
	}

	void CloseFile(VFSOpenFile *file) override { delete (MemOpen *)file; }

	bool GetFileInfo(std::string_view path, File::FileInfo *info) override {
		const ChimAsset *a = findAsset(path);
		if (!a)
			return false;
		if (info) {
			*info = File::FileInfo{};
			info->name = a->name;
			info->fullName = Path(a->name);
			info->exists = true;
			info->size = (uint64_t)(a->end - a->begin);
		}
		return true;
	}

	// Directory listing by prefix scan over the flat table (sceFont lists
	// flash0:/font, for one).
	bool GetFileListing(std::string_view path, std::vector<File::FileInfo> *listing, const char *filter) override {
		std::string prefix(path);
		if (!prefix.empty() && prefix.back() != '/')
			prefix.push_back('/');

		std::set<std::string> files, dirs;
		bool any = false;
		for (size_t i = 0; i < sizeof(g_chimAssets) / sizeof(g_chimAssets[0]); i++) {
			std::string_view name = g_chimAssets[i].name;
			if (name.substr(0, prefix.size()) != prefix)
				continue;
			any = true;
			std::string_view rest = name.substr(prefix.size());
			size_t slash = rest.find('/');
			if (slash == std::string_view::npos)
				files.emplace(rest);
			else
				dirs.emplace(rest.substr(0, slash));
		}
		if (!any)
			return false;

		listing->clear();
		for (const std::string &d : dirs) {
			File::FileInfo info{};
			info.name = d;
			info.fullName = Path(prefix + d);
			info.exists = true;
			info.isDirectory = true;
			listing->push_back(info);
		}
		for (const std::string &f : files) {
			const ChimAsset *a = findAsset(prefix + f);
			File::FileInfo info{};
			info.name = f;
			info.fullName = Path(prefix + f);
			info.exists = true;
			info.size = a ? (uint64_t)(a->end - a->begin) : 0;
			listing->push_back(info);
		}
		return true;
	}

	std::string toString() const override { return "MemoryAssets"; }
};

}  // namespace

VFSBackend *Chimera_CreateMemoryAssetReader() {
	return new MemoryAssetReader();
}
